debian/tmp/usr/bin/do-release-upgrade
debian/tmp/etc/update-manager/*
debian/tmp/usr/share/locale
debian/tmp/usr/share/ubuntu-release-upgrader/*.cfg
debian/tmp/usr/share/polkit-1/actions
debian/tmp/usr/bin/do-partial-upgrade    /usr/lib/ubuntu-release-upgrader
debian/release-upgrade-motd usr/lib/ubuntu-release-upgrader
debian/91-release-upgrade etc/update-motd.d/
debian/source_ubuntu-release-upgrader.py /usr/share/apport/package-hooks/
