debian/tmp/usr/bin/check-new-release	usr/lib/update-manager
debian/tmp/usr/bin/do-release-upgrade
debian/tmp/etc/update-manager/*
debian/tmp/usr/share/locale
debian/tmp/usr/share/update-manager/*.cfg
debian/tmp/usr/lib/python*/site-packages/UpdateManager/Core
debian/tmp/usr/lib/python*/site-packages/UpdateManager/fdsend.so
debian/tmp/usr/lib/python*/site-packages/UpdateManager/__init__.py
debian/tmp/usr/lib/python*/site-packages/DistUpgrade