#!/usr/bin/python

from optparse import OptionParser
from ChrootNonInteractive import Chroot
import os
import sys

# TODO:
# - show held-back packages 

if __name__ == "__main__":

    parser = OptionParser()
    parser.add_option("-p", "--profile", dest="profile",
                      help="write report to FILE")
    
    (options, args) = parser.parse_args()

    # init the chroot
    chroot = Chroot(options.profile, os.getcwd())
    if not chroot.bootstrap():
        sys.exit(1)
    if not chroot.upgrade():
        sys.exit(1)
