#!/bin/sh


# install additional stuff - if any


# get the ugprader and get/run it
tmp=$(mktemp)
cd $tmp
wget http://people.ubuntu.com/~mvo/.autoupgrade/dapper.tar.gz
tar xzvf dapper.tar.gz
./dapper
